// <auto-generated />
using System;
using Itinerario.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Itinerario.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261009151939_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Itinerario.Domain.Entities.EtiquetaViaje", b =>
                {
                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("viaje_id");

                    b.Property<short>("CategoriaId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoria_id");

                    b.HasKey("ViajeId", "CategoriaId");

                    b.ToTable("etiquetas_viaje", (string)null);
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.Itinerario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<short>("NumeroDia")
                        .HasColumnType("smallint")
                        .HasColumnName("numero_dia");

                    b.Property<string>("OrigenDescripcion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("origen_descripcion");

                    b.Property<decimal?>("OrigenLatitud")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("origen_latitud");

                    b.Property<decimal?>("OrigenLongitud")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("origen_longitud");

                    b.Property<string>("OrigenTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen_tipo");

                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("viaje_id");

                    b.HasKey("Id");

                    b.HasIndex("ViajeId", "NumeroDia")
                        .IsUnique();

                    b.ToTable("itinerarios", (string)null);
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.MiembroViaje", b =>
                {
                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("viaje_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset>("FechaIncorporacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_incorporacion");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("ViajeId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("miembros_viaje", (string)null);
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.ParadaItinerario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short?>("CuadrasDesdeAnterior")
                        .HasColumnType("smallint")
                        .HasColumnName("cuadras_desde_anterior");

                    b.Property<int?>("DistanciaMetrosDesdeAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("distancia_metros_desde_anterior");

                    b.Property<short?>("DuracionMinutos")
                        .HasColumnType("smallint")
                        .HasColumnName("duracion_minutos");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<Guid>("ItinerarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerario_id");

                    b.Property<Guid>("LugarId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_id");

                    b.Property<short?>("MinutosAPieDesdeAnterior")
                        .HasColumnType("smallint")
                        .HasColumnName("minutos_a_pie_desde_anterior");

                    b.Property<string>("NotasPersonales")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas_personales");

                    b.Property<short>("OrdenParada")
                        .HasColumnType("smallint")
                        .HasColumnName("orden_parada");

                    b.Property<string>("OrigenParada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen_parada");

                    b.Property<string>("SugerenciaIa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sugerencia_ia");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turno");

                    b.HasKey("Id");

                    b.HasIndex("ItinerarioId", "Turno", "OrdenParada");

                    b.ToTable("paradas_itinerario", (string)null);
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.ParametrosFamilia", b =>
                {
                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("viaje_id");

                    b.Property<short>("CantidadAcompanantes")
                        .HasColumnType("smallint")
                        .HasColumnName("cantidad_acompanantes");

                    b.Property<short>("CantidadNinos")
                        .HasColumnType("smallint")
                        .HasColumnName("cantidad_ninos");

                    b.Property<bool>("HayNinos")
                        .HasColumnType("boolean")
                        .HasColumnName("hay_ninos");

                    b.Property<bool>("MovilidadReducida")
                        .HasColumnType("boolean")
                        .HasColumnName("movilidad_reducida");

                    b.Property<bool>("RequiereMenuInfantil")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_menu_infantil");

                    b.Property<bool>("RequiereRitmoBajo")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_ritmo_bajo");

                    b.HasKey("ViajeId");

                    b.ToTable("parametros_familia", (string)null);
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.Viaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlcanceTemporal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alcance_temporal");

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barrio");

                    b.Property<string>("CodigoInvitacion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("codigo_invitacion");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<string>("DireccionPartida")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion_partida");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Borrador")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<decimal?>("LatitudPartida")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitud_partida");

                    b.Property<short?>("LimiteCuadrasEntreParadas")
                        .HasColumnType("smallint")
                        .HasColumnName("limite_cuadras_entre_paradas");

                    b.Property<decimal?>("LongitudPartida")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitud_partida");

                    b.Property<Guid?>("LugarPartidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lugar_partida_id");

                    b.Property<string>("NivelPresupuesto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel_presupuesto");

                    b.Property<string>("NombrePuntoPartida")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_punto_partida");

                    b.Property<string>("RitmoCaminata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ritmo_caminata");

                    b.Property<string>("TipoPuntoPartida")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_punto_partida");

                    b.Property<string>("TipoViaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_viaje");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInvitacion")
                        .IsUnique();

                    b.HasIndex("CreadoPorUsuarioId");

                    b.ToTable("viajes", (string)null);
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.EtiquetaViaje", b =>
                {
                    b.HasOne("Itinerario.Domain.Entities.Viaje", "Viaje")
                        .WithMany("Etiquetas")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.Itinerario", b =>
                {
                    b.HasOne("Itinerario.Domain.Entities.Viaje", "Viaje")
                        .WithMany("Itinerarios")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.MiembroViaje", b =>
                {
                    b.HasOne("Itinerario.Domain.Entities.Viaje", "Viaje")
                        .WithMany("Miembros")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.ParadaItinerario", b =>
                {
                    b.HasOne("Itinerario.Domain.Entities.Itinerario", "Itinerario")
                        .WithMany("Paradas")
                        .HasForeignKey("ItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerario");
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.ParametrosFamilia", b =>
                {
                    b.HasOne("Itinerario.Domain.Entities.Viaje", "Viaje")
                        .WithOne("ParametrosFamilia")
                        .HasForeignKey("Itinerario.Domain.Entities.ParametrosFamilia", "ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.Itinerario", b =>
                {
                    b.Navigation("Paradas");
                });

            modelBuilder.Entity("Itinerario.Domain.Entities.Viaje", b =>
                {
                    b.Navigation("Etiquetas");

                    b.Navigation("Itinerarios");

                    b.Navigation("Miembros");

                    b.Navigation("ParametrosFamilia");
                });
#pragma warning restore 612, 618
        }
    }
}
